import React from 'react';
import { PageHeader } from '../components/quant/PageHeader';
import { Disclaimer } from '../components/quant/Disclaimer';
import { FreshnessBadge, SourceBadge } from '../components/quant/FreshnessBadge';
import { useDrawer } from '../components/quant/DataDrawer';
import { useProviderHealth } from '../hooks/useProviders';
import { DatasetDrawerBody, type DatasetInfo } from '../components/quant/DatasetDrawerBody';
import { RefreshCw, CheckCircle2, XCircle } from 'lucide-react';

const DATASETS: DatasetInfo[] = [
  {
    zone: 'dq_raw', name: 'finnhub_quotes', provider: 'finnhub', cadence: '1 min',
    description: 'Raw real-time quote snapshots from Finnhub /quote, captured at request time.',
    schema: [
      { field: 'symbol',          type: 'STRING' },
      { field: 'price',           type: 'FLOAT64' },
      { field: 'change',          type: 'FLOAT64' },
      { field: 'change_pct',      type: 'FLOAT64' },
      { field: 'high', type: 'FLOAT64' }, { field: 'low', type: 'FLOAT64' },
      { field: 'open', type: 'FLOAT64' }, { field: 'previous_close', type: 'FLOAT64' },
      { field: 'ts_ms',           type: 'INT64', note: 'exchange timestamp · unix ms' },
    ],
    qualityNotes: ['Free tier: 60 req/min', 'Gateway caches 1 min', 'No historical persistence yet'],
    status: 'partial',
  },
  {
    zone: 'dq_raw', name: 'twelvedata_ohlcv', provider: 'twelve_data', cadence: '5 min / 6 h',
    description: 'OHLCV bars for equities, ETFs, FX and crypto across daily/weekly/monthly intervals.',
    schema: [
      { field: 'symbol', type: 'STRING' },
      { field: 'ts_ms',  type: 'INT64' },
      { field: 'open',   type: 'FLOAT64' }, { field: 'high', type: 'FLOAT64' },
      { field: 'low',    type: 'FLOAT64' }, { field: 'close', type: 'FLOAT64' },
      { field: 'volume', type: 'FLOAT64', note: 'may be 0 for FX' },
      { field: 'interval', type: 'STRING' },
    ],
    qualityNotes: ['Free tier: 800 req/day', 'Daily bars cached 6h', 'Intraday cached 5 min'],
    status: 'wired',
  },
  {
    zone: 'dq_raw', name: 'av_macro', provider: 'alpha_vantage', cadence: '6 h',
    description: 'Alpha Vantage macroeconomic time-series: Fed funds, CPI, DGS10/2, unemployment, real GDP.',
    schema: [
      { field: 'series_id', type: 'STRING' }, { field: 'ts_ms', type: 'INT64' },
      { field: 'value', type: 'FLOAT64' }, { field: 'unit', type: 'STRING' },
      { field: 'frequency', type: 'STRING' },
    ],
    qualityNotes: ['Hard limit: 25 req/day on free tier', 'Cached 6h', 'Series ids: FEDFUNDS, CPI, DGS10, DGS2, UNEMP, GDP'],
    status: 'wired',
  },
  {
    zone: 'dq_raw', name: 'tavily_results', provider: 'tavily', cadence: '1 h',
    description: 'Tavily web research results with optional Gemini-friendly answer synthesis.',
    schema: [
      { field: 'query', type: 'STRING' }, { field: 'url', type: 'STRING' },
      { field: 'title', type: 'STRING' }, { field: 'content', type: 'STRING' },
      { field: 'score', type: 'FLOAT64' }, { field: 'published_at', type: 'STRING', note: 'ISO date if present' },
    ],
    qualityNotes: ['Topic-aware (finance / news / general)', 'Days param caps lookback'],
    status: 'wired',
  },
  {
    zone: 'dq_raw', name: 'serper_results', provider: 'serper', cadence: '1 h',
    description: 'Google search + news passthrough via Serper, used as a fast headline backup.',
    schema: [
      { field: 'query', type: 'STRING' }, { field: 'title', type: 'STRING' },
      { field: 'link', type: 'STRING' }, { field: 'snippet', type: 'STRING' },
      { field: 'source', type: 'STRING' }, { field: 'date', type: 'STRING', note: 'free-form provider date' },
    ],
    qualityNotes: ['Cheap fallback when Tavily is rate-limited', 'No structured published_at'],
    status: 'wired',
  },
  {
    zone: 'dq_cleaned', name: 'ohlcv', provider: 'derived', cadence: 'planned',
    description: 'Normalised OHLCV unioned across providers, timezone-aligned, gap-filled.',
    schema: [{ field: 'symbol', type: 'STRING' }, { field: 'ts_ms', type: 'INT64' }, { field: 'close', type: 'FLOAT64' }],
    qualityNotes: ['Pending BigQuery dq_cleaned zone'],
    status: 'planned',
  },
  {
    zone: 'dq_features', name: 'returns', provider: 'derived', cadence: 'planned',
    description: 'Log/simple returns derived from cleaned OHLCV, indexed by symbol+timeframe.',
    schema: [
      { field: 'symbol', type: 'STRING' }, { field: 'ts_ms', type: 'INT64' },
      { field: 'log_return', type: 'FLOAT64' }, { field: 'simple_return', type: 'FLOAT64' },
    ],
    qualityNotes: ['Currently computed client-side in Quant Lab / Cross-Asset'],
    status: 'planned',
  },
  {
    zone: 'dq_research', name: 'briefings', provider: 'firestore', cadence: 'on demand',
    description: 'Persisted institutional briefings generated by the /v1/briefings/generate gateway route.',
    schema: [
      { field: 'kind', type: 'STRING' }, { field: 'title', type: 'STRING' },
      { field: 'summary', type: 'STRING' }, { field: 'body', type: 'STRING', note: 'markdown' },
      { field: 'highlights', type: 'STRING[]' }, { field: 'symbols', type: 'STRING[]' },
      { field: 'created_at', type: 'TIMESTAMP' },
    ],
    qualityNotes: ['Persisted under workspaces/{w}/projects/{p}/briefings', 'Admin-write only'],
    status: 'wired',
  },
];

const ZONE_HINT: Record<string, string> = {
  dq_raw:      'Exact source data, immutable',
  dq_cleaned:  'Normalised, time-aligned',
  dq_features: 'Engineered ML-ready features',
  dq_research: 'Artifacts, model outputs, briefings',
};

export const WarehouseExplorer: React.FC = () => {
  const drawer = useDrawer();
  const health = useProviderHealth();

  const byZone = DATASETS.reduce((acc, d) => {
    (acc[d.zone] ??= []).push(d);
    return acc;
  }, {} as Record<string, DatasetInfo[]>);

  return (
    <div style={{ padding: '0 24px 32px', maxWidth: 1200, margin: '0 auto' }}>
      <PageHeader
        title="Data Warehouse Explorer"
        subtitle="Operational view of the providers and datasets feeding Deplyze Quant. BigQuery cleaned / features zones land in a later phase."
        actions={
          <div style={{ display: 'inline-flex', gap: 6, alignItems: 'center' }}>
            <FreshnessBadge status={health.status} fetchedAt={health.fetchedAt} compact />
            <button
              onClick={() => health.refresh()}
              title="Re-check providers"
              style={{
                width: 26, height: 26, borderRadius: 6,
                border: '1px solid var(--border)', background: 'var(--card)',
                color: 'var(--muted-foreground)', cursor: 'pointer',
                display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
              }}
            >
              <RefreshCw size={12} style={{ animation: health.isFetching ? 'spin 1s linear infinite' : undefined }} />
            </button>
          </div>
        }
      />

      {/* Provider health */}
      <section style={{ marginBottom: 18 }}>
        <h2 className="ds-heading" style={{ marginBottom: 8 }}>Providers</h2>
        {health.loading && !health.data ? (
          <p className="ds-caption" style={{ color: 'var(--muted-foreground)' }}>Checking provider health…</p>
        ) : health.error && !health.data ? (
          <p className="ds-caption" style={{ color: 'var(--primary)' }}>
            Provider health unavailable: {health.error.message}{' '}
            <button onClick={() => health.refresh()} style={{
              background: 'transparent', border: 'none', color: 'var(--primary)',
              textDecoration: 'underline', cursor: 'pointer', padding: 0, fontSize: 'inherit',
            }}>Retry</button>
          </p>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 8 }}>
            {(health.data ?? []).map((p) => {
              const ok = p.configured;
              return (
                <div key={p.id} className="ds-surface" style={{ padding: 10, borderRadius: 8, display: 'flex', alignItems: 'center', gap: 8 }}>
                  {ok ? <CheckCircle2 size={16} color="#4E6040" /> : <XCircle size={16} color="var(--primary)" />}
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--foreground)' }}>
                      {p.id.replace('_', ' ')}
                    </div>
                    <div className="ds-caption" style={{ color: 'var(--muted-foreground)' }}>
                      {ok ? 'configured' : 'not configured'}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
        <p className="ds-caption" style={{ marginTop: 8, color: 'var(--muted-foreground)' }}>
          The gateway's <code>/providers/health</code> currently only reports configuration status. Per-provider
          latency, last-success timestamp, and quota tracking will land alongside the BigQuery
          <code> dq_audit</code> zone.
        </p>
      </section>

      {/* Datasets by zone */}
      {Object.keys(byZone).map((zone) => (
        <section key={zone} style={{ marginBottom: 18 }}>
          <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 8 }}>
            <h2 className="ds-heading" style={{ margin: 0, fontFamily: 'ui-monospace, monospace' }}>{zone}</h2>
            <span className="ds-caption" style={{ color: 'var(--muted-foreground)' }}>{ZONE_HINT[zone] ?? ''}</span>
          </header>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 8 }}>
            {byZone[zone].map((ds) => (
              <button
                key={ds.name}
                onClick={() => drawer.open({
                  title: ds.name,
                  subtitle: `${zone} · ${ds.provider}`,
                  width: 560,
                  body: <DatasetDrawerBody ds={ds} />,
                })}
                className="ds-surface ds-transition-fast"
                style={{
                  textAlign: 'left', padding: 12, borderRadius: 10,
                  border: '1px solid var(--border)', background: 'var(--card)',
                  cursor: 'pointer', color: 'inherit', display: 'grid', gap: 4,
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 6 }}>
                  <span style={{ fontFamily: 'ui-monospace, monospace', fontSize: 12, fontWeight: 700 }}>{ds.name}</span>
                  <SourceBadge source={ds.provider} />
                </div>
                <p className="ds-caption" style={{ margin: 0, color: 'var(--muted-foreground)' }}>{ds.description}</p>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 }}>
                  <span className="ds-caption" style={{ color: 'var(--muted-foreground)' }}>cadence · {ds.cadence}</span>
                  <span style={{
                    padding: '1px 7px', borderRadius: 999,
                    fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase',
                    color: ds.status === 'wired' ? '#4E6040' : ds.status === 'partial' ? '#9e7e3a' : 'var(--muted-foreground)',
                    background: ds.status === 'wired' ? 'rgba(78,96,64,0.10)'
                      : ds.status === 'partial' ? 'rgba(158,126,58,0.10)'
                      : 'var(--muted)',
                    border: '1px solid color-mix(in srgb, currentColor 25%, transparent)',
                  }}>
                    {ds.status}
                  </span>
                </div>
              </button>
            ))}
          </div>
        </section>
      ))}

      <Disclaimer />
      <style>{`@keyframes spin { from { transform: rotate(0) } to { transform: rotate(360deg) } }`}</style>
    </div>
  );
};
