/**
 * generate-sitemap.mjs — emit public/sitemap.xml.
 *
 * Combines the stable public routes with one URL per curated instrument so the
 * per-symbol detail pages (the most SEO-valuable surface) are discoverable.
 * Run manually or in CI before deploy:
 *
 *   node scripts/generate-sitemap.mjs
 *
 * Per-briefing URLs are intentionally omitted — they require querying published
 * briefings (BigQuery/Firestore) and are best emitted by a server-side job.
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = 'https://app.deplyze.com';

// Stable public entry points (keep in sync with src/lib/access.ts).
const STATIC_ROUTES = [
  { path: '/', changefreq: 'hourly', priority: '1.0' },
  { path: '/terminal', changefreq: 'hourly', priority: '0.9' },
  { path: '/macro', changefreq: 'hourly', priority: '0.9' },
  { path: '/relations-map', changefreq: 'daily', priority: '0.8' },
  { path: '/historical-intelligence', changefreq: 'daily', priority: '0.8' },
  { path: '/briefings', changefreq: 'hourly', priority: '0.8' },
  { path: '/market/world-equity', changefreq: 'hourly', priority: '0.7' },
  { path: '/market/us-sectors', changefreq: 'hourly', priority: '0.7' },
  { path: '/market/global-yields', changefreq: 'hourly', priority: '0.7' },
  { path: '/market/countries', changefreq: 'hourly', priority: '0.7' },
  { path: '/market/commodities', changefreq: 'hourly', priority: '0.7' },
  { path: '/market/fx-liquidity', changefreq: 'hourly', priority: '0.7' },
];

// Curated, liquid instruments with public detail pages. Expand as needed.
const INSTRUMENTS = [
  // Index / broad ETFs
  'SPY', 'QQQ', 'IWM', 'DIA', 'VTI', 'TLT', 'HYG', 'LQD', 'GLD', 'SLV', 'USO', 'UUP',
  // US mega-caps
  'AAPL', 'MSFT', 'NVDA', 'AMZN', 'GOOGL', 'META', 'TSLA', 'AVGO', 'BRK.B', 'JPM',
  'V', 'MA', 'UNH', 'XOM', 'JNJ', 'WMT', 'PG', 'HD', 'COST', 'BAC', 'KO', 'PEP',
  'AMD', 'NFLX', 'CRM', 'ORCL', 'ADBE', 'INTC', 'CSCO', 'DIS',
];

function urlEntry({ loc, changefreq, priority }) {
  return `  <url><loc>${loc}</loc>${changefreq ? `<changefreq>${changefreq}</changefreq>` : ''}${priority ? `<priority>${priority}</priority>` : ''}</url>`;
}

const lines = [];
for (const r of STATIC_ROUTES) {
  lines.push(urlEntry({ loc: `${SITE}${r.path}`, changefreq: r.changefreq, priority: r.priority }));
}
for (const sym of INSTRUMENTS) {
  lines.push(urlEntry({ loc: `${SITE}/instruments/${encodeURIComponent(sym)}`, changefreq: 'daily', priority: '0.6' }));
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${lines.join('\n')}
</urlset>
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml');
writeFileSync(out, xml, 'utf8');
console.log(`[sitemap] wrote ${STATIC_ROUTES.length + INSTRUMENTS.length} urls → ${out}`);
