import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles } from 'lucide-react';
import { useAgentOutputs } from '../../hooks/useAgentIntelligence';
import { SectionCard } from './SectionCard';
import { relTime, stripMarkdown } from './format';
import { AGENT_DOMAIN_LABELS } from '../../types/agents';
import type { AgentOutput } from '../../types/agents';
import { severityConfig } from '../../lib/semanticPalette';

const Card: React.FC<{ o: AgentOutput }> = ({ o }) => {
  const navigate = useNavigate();
  const sevC = severityConfig(o.severity).color;
  return (
    <button
      type="button"
      onClick={() => navigate(`/artifacts/${encodeURIComponent(o.artifact_id)}`)}
      className="ds-transition-fast"
      style={{
        display: 'flex', flexDirection: 'column', gap: 7, textAlign: 'left', minWidth: 0,
        padding: '12px 13px', borderRadius: 8, border: '1px solid var(--border)',
        background: 'transparent', cursor: 'pointer',
      }}
      onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.background = 'color-mix(in srgb, var(--primary) 4%, transparent)'; }}
      onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.background = 'transparent'; }}
    >
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}>
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: sevC }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: sevC, flexShrink: 0 }} />
          {AGENT_DOMAIN_LABELS[o.domain] ?? o.domain}
        </span>
        <span style={{ fontSize: 10, color: 'var(--muted-foreground)' }}>{relTime(o.generated_at)}</span>
      </div>
      <p style={{ margin: 0, fontSize: 12, fontWeight: 700, lineHeight: 1.3, color: 'var(--foreground)', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
        {stripMarkdown(o.title) || 'Intelligence observation'}
      </p>
      {o.summary && (
        <p style={{ margin: 0, fontSize: 11, lineHeight: 1.45, color: 'var(--muted-foreground)', display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
          {stripMarkdown(o.summary)}
        </p>
      )}
      {o.symbols.length > 0 && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
          {o.symbols.slice(0, 4).map((s) => (
            <span key={s} style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.04em', color: 'var(--primary)' }}>{s}</span>
          ))}
        </div>
      )}
    </button>
  );
};

export const IntelligenceSpotlight: React.FC = () => {
  const { data, loading, error } = useAgentOutputs({ limit: 6 });
  const items = (data ?? []).slice(0, 6);

  return (
    <SectionCard
      title="Deplyze Intelligence Spotlight"
      subtitle="Agent-generated research signals"
      action={<Sparkles size={15} style={{ color: 'var(--primary)' }} />}
    >
      {loading && items.length === 0 ? (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 10 }}>
          {Array.from({ length: 3 }).map((_, i) => <div key={i} style={{ height: 110, borderRadius: 8, background: 'var(--muted)', animation: 'pulse 1.8s infinite' }} />)}
        </div>
      ) : error && items.length === 0 ? (
        <p className="ds-caption" style={{ color: 'var(--muted-foreground)', padding: '14px 2px' }}>Intelligence signals are temporarily unavailable.</p>
      ) : items.length === 0 ? (
        <p className="ds-caption" style={{ color: 'var(--muted-foreground)', padding: '14px 2px' }}>No recent observations.</p>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 10 }}>
          {items.map((o) => <Card key={o.artifact_id} o={o} />)}
        </div>
      )}
      <p style={{ margin: '10px 2px 0', fontSize: 10, color: 'var(--muted-foreground)', lineHeight: 1.4 }}>
        Probabilistic research intelligence generated by Deplyze agents — context for your own analysis, not trade recommendations.
      </p>
    </SectionCard>
  );
};
