/**
 * generateBriefingSitemap.ts — emit a sitemap of public briefing detail pages.
 *
 * The static scripts/generate-sitemap.mjs covers stable routes + curated
 * instruments. Briefings are dynamic and live in Firestore at
 *   workspaces/{wid}/projects/{pid}/briefings/{briefingId}
 * so they need a server-side job (Admin SDK) to enumerate them. This is the
 * server-side counterpart, intended to run on a schedule (Cloud Scheduler ->
 * Cloud Run job) and either print the XML or write it to a file the hosting
 * deploy picks up.
 *
 *   npx tsx src/scripts/generateBriefingSitemap.ts                 # print to stdout
 *   npx tsx src/scripts/generateBriefingSitemap.ts --out=sitemap-briefings.xml
 *   npx tsx src/scripts/generateBriefingSitemap.ts --limit=5000 --days=180
 *
 * Requires FIREBASE_PROJECT_ID and Application Default Credentials with
 * Firestore read access.
 *
 * NOTE (scaffold): briefings are currently workspace-private — there is no
 * `visibility: 'public'` concept yet. Until one exists, this job is gated OFF
 * by default (returns zero URLs) so it can never leak private research into a
 * crawlable sitemap. Flip PUBLIC_BRIEFINGS_ENABLED (or wire the real filter at
 * the marked TODO) once a public-briefing surface ships.
 */

import { writeFileSync } from 'node:fs';
import { initializeApp, getApps } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

const SITE = process.env.PUBLIC_SITE_ORIGIN || 'https://app.deplyze.com';

// Hard gate: no public-briefing surface exists yet, so emit nothing by default.
// Set PUBLIC_BRIEFINGS_ENABLED=true (and implement the filter below) to enable.
const PUBLIC_BRIEFINGS_ENABLED = process.env.PUBLIC_BRIEFINGS_ENABLED === 'true';

function arg(name: string): string | undefined {
  const hit = process.argv.find((a) => a === `--${name}` || a.startsWith(`--${name}=`));
  if (!hit) return undefined;
  const eq = hit.indexOf('=');
  return eq >= 0 ? hit.slice(eq + 1) : 'true';
}

const OUT = arg('out');
const LIMIT = Number(arg('limit') ?? '5000');
const DAYS = Number(arg('days') ?? '365');
const cutoffMs = Date.now() - DAYS * 24 * 60 * 60 * 1000;

interface BriefingUrl {
  id: string;
  updatedMs: number;
}

function urlEntry({ id, updatedMs }: BriefingUrl): string {
  const loc = `${SITE}/briefings/${encodeURIComponent(id)}`;
  const lastmod = new Date(updatedMs || Date.now()).toISOString().slice(0, 10);
  return `  <url><loc>${loc}</loc><lastmod>${lastmod}</lastmod><changefreq>weekly</changefreq><priority>0.6</priority></url>`;
}

async function collectPublicBriefings(): Promise<BriefingUrl[]> {
  if (!PUBLIC_BRIEFINGS_ENABLED) {
    console.warn('[briefing-sitemap] PUBLIC_BRIEFINGS_ENABLED is not set — emitting 0 URLs (no public-briefing surface yet).');
    return [];
  }

  if (getApps().length === 0) {
    initializeApp({ projectId: process.env.FIREBASE_PROJECT_ID });
  }
  const db = getFirestore();

  // collectionGroup spans every workspace/project briefings subcollection.
  // TODO(public-briefings): once a public-briefing surface ships, replace this
  // with `.where('visibility', '==', 'public')` (+ a composite index) so only
  // intentionally-published briefings are crawlable. Until then this code path
  // is unreachable because of the PUBLIC_BRIEFINGS_ENABLED gate above.
  const snap = await db.collectionGroup('briefings').limit(LIMIT).get();

  const urls: BriefingUrl[] = [];
  for (const doc of snap.docs) {
    const data = doc.data() as { createdAt?: { toMillis?: () => number }; updatedAt?: { toMillis?: () => number }; visibility?: string };
    if (data.visibility !== 'public') continue; // defensive: never emit private briefings
    const updatedMs = data.updatedAt?.toMillis?.() ?? data.createdAt?.toMillis?.() ?? 0;
    if (updatedMs && updatedMs < cutoffMs) continue;
    urls.push({ id: doc.id, updatedMs });
  }
  return urls;
}

function buildXml(urls: BriefingUrl[]): string {
  const lines = urls.map(urlEntry);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by cloud-run/gateway/src/scripts/generateBriefingSitemap.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${lines.join('\n')}
</urlset>
`;
}

async function main(): Promise<void> {
  const urls = await collectPublicBriefings();
  const xml = buildXml(urls);
  if (OUT) {
    writeFileSync(OUT, xml, 'utf8');
    console.log(`[briefing-sitemap] wrote ${urls.length} briefing urls -> ${OUT}`);
  } else {
    process.stdout.write(xml);
    console.error(`[briefing-sitemap] emitted ${urls.length} briefing urls to stdout`);
  }
}

main().catch((err) => {
  console.error('[briefing-sitemap] failed:', err);
  process.exit(1);
});
